//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 02:54:08 PM CEST 
//

package org.ow2.sirocco.cloudmanager.service.ovf.datamodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * org.ow2.sirocco.cloudmanager.service.ovf.datamodel package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ElementName_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "ElementName");

    private static final QName _CIMResourceAllocationSettingData_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData",
        "CIM_ResourceAllocationSettingData");

    private static final QName _ProductSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "ProductSection");

    private static final QName _DefaultValue_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/common", "DefaultValue");

    private static final QName _RecoveryFile_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "RecoveryFile");

    private static final QName _CIMVirtualSystemSettingData_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "CIM_VirtualSystemSettingData");

    private static final QName _InstallSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "InstallSection");

    private static final QName _ConfigurationFile_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ConfigurationFile");

    private static final QName _PoolID_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "PoolID");

    private static final QName _Weight_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "Weight");

    private static final QName _VirtualSystemCollection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1",
        "VirtualSystemCollection");

    private static final QName _VirtualSystem_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "VirtualSystem");

    private static final QName _SuspendDataRoot_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "SuspendDataRoot");

    private static final QName _VirtualSystemIdentifier_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "VirtualSystemIdentifier");

    private static final QName _AddressOnParent_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "AddressOnParent");

    private static final QName _DiskSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "DiskSection");

    private static final QName _Parent_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "Parent");

    private static final QName _ResourceSubType_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "ResourceSubType");

    private static final QName _AutomaticShutdownAction_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticShutdownAction");

    private static final QName _Limit_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "Limit");

    private static final QName _SwapFileDataRoot_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "SwapFileDataRoot");

    private static final QName _DeploymentOptionSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1",
        "DeploymentOptionSection");

    private static final QName _StartupSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "StartupSection");

    private static final QName _AutomaticStartupActionSequenceNumber_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData",
        "AutomaticStartupActionSequenceNumber");

    private static final QName _AutomaticAllocation_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "AutomaticAllocation");

    private static final QName _AutomaticStartupActionDelay_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticStartupActionDelay");

    private static final QName _Reservation_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "Reservation");

    private static final QName _VirtualHardwareSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1",
        "VirtualHardwareSection");

    private static final QName _VirtualSystemType_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "VirtualSystemType");

    private static final QName _OtherResourceType_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "OtherResourceType");

    private static final QName _Connection_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "Connection");

    private static final QName _ResourceAllocationSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1",
        "ResourceAllocationSection");

    private static final QName _Strings_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "Strings");

    private static final QName _Section_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "Section");

    private static final QName _AutomaticRecoveryAction_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticRecoveryAction");

    private static final QName _Envelope_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "Envelope");

    private static final QName _AutomaticStartupAction_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticStartupAction");

    private static final QName _ConfigurationID_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ConfigurationID");

    private static final QName _VirtualQuantityUnits_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "VirtualQuantityUnits");

    private static final QName _OperatingSystemSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1",
        "OperatingSystemSection");

    private static final QName _ResourceType_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "ResourceType");

    private static final QName _AllocationUnits_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "AllocationUnits");

    private static final QName _ConsumerVisibility_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "ConsumerVisibility");

    private static final QName _Notes_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "Notes");

    private static final QName _CreationTime_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "CreationTime");

    private static final QName _SnapshotDataRoot_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "SnapshotDataRoot");

    private static final QName _VirtualQuantity_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "VirtualQuantity");

    private static final QName _Content_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "Content");

    private static final QName _InstanceID_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "InstanceID");

    private static final QName _ConfigurationDataRoot_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ConfigurationDataRoot");

    private static final QName _HostResource_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "HostResource");

    private static final QName _Description_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "Description");

    private static final QName _LogDataRoot_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "LogDataRoot");

    private static final QName _AutomaticDeallocation_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "AutomaticDeallocation");

    private static final QName _MappingBehavior_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "MappingBehavior");

    private static final QName _Address_QNAME = new QName(
        "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", "Address");

    private static final QName _AnnotationSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1",
        "AnnotationSection");

    private static final QName _NetworkSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "NetworkSection");

    private static final QName _EulaSection_QNAME = new QName("http://schemas.dmtf.org/ovf/envelope/1", "EulaSection");

    private static final QName _CimDateTimeCIMDateTime_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/common",
        "CIM_DateTime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * org.ow2.sirocco.cloudmanager.service.ovf.datamodel
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeploymentOptionSectionType }
     */
    public DeploymentOptionSectionType createDeploymentOptionSectionType() {
        return new DeploymentOptionSectionType();
    }

    /**
     * Create an instance of {@link MsgType }
     */
    public MsgType createMsgType() {
        return new MsgType();
    }

    /**
     * Create an instance of {@link PropertyConfigurationValueType }
     */
    public PropertyConfigurationValueType createPropertyConfigurationValueType() {
        return new PropertyConfigurationValueType();
    }

    /**
     * Create an instance of {@link StringsType }
     */
    public StringsType createStringsType() {
        return new StringsType();
    }

    /**
     * Create an instance of {@link VirtualSystemType }
     */
    public VirtualSystemType createVirtualSystemType() {
        return new VirtualSystemType();
    }

    /**
     * Create an instance of {@link CimDouble }
     */
    public CimDouble createCimDouble() {
        return new CimDouble();
    }

    /**
     * Create an instance of {@link AutomaticStartupAction }
     */
    public AutomaticStartupAction createAutomaticStartupAction() {
        return new AutomaticStartupAction();
    }

    /**
     * Create an instance of {@link VirtualHardwareSectionType }
     */
    public VirtualHardwareSectionType createVirtualHardwareSectionType() {
        return new VirtualHardwareSectionType();
    }

    /**
     * Create an instance of {@link QualifierString }
     */
    public QualifierString createQualifierString() {
        return new QualifierString();
    }

    /**
     * Create an instance of {@link AutomaticShutdownAction }
     */
    public AutomaticShutdownAction createAutomaticShutdownAction() {
        return new AutomaticShutdownAction();
    }

    /**
     * Create an instance of {@link ResourceAllocationCaption.Type }
     */
    public ResourceAllocationCaption.Type createResourceAllocationCaptionType() {
        return new ResourceAllocationCaption.Type();
    }

    /**
     * Create an instance of {@link CimUnsignedLong }
     */
    public CimUnsignedLong createCimUnsignedLong() {
        return new CimUnsignedLong();
    }

    /**
     * Create an instance of {@link CimAnySimpleType }
     */
    public CimAnySimpleType createCimAnySimpleType() {
        return new CimAnySimpleType();
    }

    /**
     * Create an instance of {@link StartupSectionType }
     */
    public StartupSectionType createStartupSectionType() {
        return new StartupSectionType();
    }

    /**
     * Create an instance of {@link OperatingSystemSectionType }
     */
    public OperatingSystemSectionType createOperatingSystemSectionType() {
        return new OperatingSystemSectionType();
    }

    /**
     * Create an instance of {@link CimFloat }
     */
    public CimFloat createCimFloat() {
        return new CimFloat();
    }

    /**
     * Create an instance of {@link StartupSectionType.Item }
     */
    public StartupSectionType.Item createStartupSectionTypeItem() {
        return new StartupSectionType.Item();
    }

    /**
     * Create an instance of {@link ConsumerVisibility }
     */
    public ConsumerVisibility createConsumerVisibility() {
        return new ConsumerVisibility();
    }

    /**
     * Create an instance of {@link VSSDType }
     */
    public VSSDType createVSSDType() {
        return new VSSDType();
    }

    /**
     * Create an instance of {@link CimLong }
     */
    public CimLong createCimLong() {
        return new CimLong();
    }

    /**
     * Create an instance of {@link CimChar16 }
     */
    public CimChar16 createCimChar16() {
        return new CimChar16();
    }

    /**
     * Create an instance of {@link CimShort }
     */
    public CimShort createCimShort() {
        return new CimShort();
    }

    /**
     * Create an instance of {@link DeploymentOptionSectionType.Configuration }
     */
    public DeploymentOptionSectionType.Configuration createDeploymentOptionSectionTypeConfiguration() {
        return new DeploymentOptionSectionType.Configuration();
    }

    /**
     * Create an instance of {@link StringsType.Msg }
     */
    public StringsType.Msg createStringsTypeMsg() {
        return new StringsType.Msg();
    }

    /**
     * Create an instance of {@link CIMVirtualSystemSettingDataType }
     */
    public CIMVirtualSystemSettingDataType createCIMVirtualSystemSettingDataType() {
        return new CIMVirtualSystemSettingDataType();
    }

    /**
     * Create an instance of {@link QualifierSInt64 }
     */
    public QualifierSInt64 createQualifierSInt64() {
        return new QualifierSInt64();
    }

    /**
     * Create an instance of {@link QualifierSArray }
     */
    public QualifierSArray createQualifierSArray() {
        return new QualifierSArray();
    }

    /**
     * Create an instance of {@link MappingBehavior }
     */
    public MappingBehavior createMappingBehavior() {
        return new MappingBehavior();
    }

    /**
     * Create an instance of {@link CimString }
     */
    public CimString createCimString() {
        return new CimString();
    }

    /**
     * Create an instance of {@link VirtualSystemCollectionType }
     */
    public VirtualSystemCollectionType createVirtualSystemCollectionType() {
        return new VirtualSystemCollectionType();
    }

    /**
     * Create an instance of {@link ProductSectionType.Icon }
     */
    public ProductSectionType.Icon createProductSectionTypeIcon() {
        return new ProductSectionType.Icon();
    }

    /**
     * Create an instance of {@link CimInt }
     */
    public CimInt createCimInt() {
        return new CimInt();
    }

    /**
     * Create an instance of {@link ReferencesType }
     */
    public ReferencesType createReferencesType() {
        return new ReferencesType();
    }

    /**
     * Create an instance of {@link CimUnsignedByte }
     */
    public CimUnsignedByte createCimUnsignedByte() {
        return new CimUnsignedByte();
    }

    /**
     * Create an instance of {@link InstallSectionType }
     */
    public InstallSectionType createInstallSectionType() {
        return new InstallSectionType();
    }

    /**
     * Create an instance of {@link EulaSectionType }
     */
    public EulaSectionType createEulaSectionType() {
        return new EulaSectionType();
    }

    /**
     * Create an instance of {@link QualifierBoolean }
     */
    public QualifierBoolean createQualifierBoolean() {
        return new QualifierBoolean();
    }

    /**
     * Create an instance of {@link CimBoolean }
     */
    public CimBoolean createCimBoolean() {
        return new CimBoolean();
    }

    /**
     * Create an instance of {@link CimBase64Binary }
     */
    public CimBase64Binary createCimBase64Binary() {
        return new CimBase64Binary();
    }

    /**
     * Create an instance of {@link CimByte }
     */
    public CimByte createCimByte() {
        return new CimByte();
    }

    /**
     * Create an instance of {@link EnvelopeType }
     */
    public EnvelopeType createEnvelopeType() {
        return new EnvelopeType();
    }

    /**
     * Create an instance of {@link AnnotationSectionType }
     */
    public AnnotationSectionType createAnnotationSectionType() {
        return new AnnotationSectionType();
    }

    /**
     * Create an instance of {@link CimReference }
     */
    public CimReference createCimReference() {
        return new CimReference();
    }

    /**
     * Create an instance of {@link NetworkSectionType.Network }
     */
    public NetworkSectionType.Network createNetworkSectionTypeNetwork() {
        return new NetworkSectionType.Network();
    }

    /**
     * Create an instance of {@link ProductSectionType.Property }
     */
    public ProductSectionType.Property createProductSectionTypeProperty() {
        return new ProductSectionType.Property();
    }

    /**
     * Create an instance of {@link VirtualSystemCaption.Type }
     */
    public VirtualSystemCaption.Type createVirtualSystemCaptionType() {
        return new VirtualSystemCaption.Type();
    }

    /**
     * Create an instance of {@link CimDateTime }
     */
    public CimDateTime createCimDateTime() {
        return new CimDateTime();
    }

    /**
     * Create an instance of {@link FileType }
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link CimUnsignedShort }
     */
    public CimUnsignedShort createCimUnsignedShort() {
        return new CimUnsignedShort();
    }

    /**
     * Create an instance of {@link CIMResourceAllocationSettingDataType }
     */
    public CIMResourceAllocationSettingDataType createCIMResourceAllocationSettingDataType() {
        return new CIMResourceAllocationSettingDataType();
    }

    /**
     * Create an instance of {@link RASDType }
     */
    public RASDType createRASDType() {
        return new RASDType();
    }

    /**
     * Create an instance of {@link ProductSectionType }
     */
    public ProductSectionType createProductSectionType() {
        return new ProductSectionType();
    }

    /**
     * Create an instance of {@link QualifierUInt32 }
     */
    public QualifierUInt32 createQualifierUInt32() {
        return new QualifierUInt32();
    }

    /**
     * Create an instance of {@link DiskSectionType }
     */
    public DiskSectionType createDiskSectionType() {
        return new DiskSectionType();
    }

    /**
     * Create an instance of {@link ResourceAllocationSectionType }
     */
    public ResourceAllocationSectionType createResourceAllocationSectionType() {
        return new ResourceAllocationSectionType();
    }

    /**
     * Create an instance of {@link VirtualDiskDescType }
     */
    public VirtualDiskDescType createVirtualDiskDescType() {
        return new VirtualDiskDescType();
    }

    /**
     * Create an instance of {@link ResourceType }
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link NetworkSectionType }
     */
    public NetworkSectionType createNetworkSectionType() {
        return new NetworkSectionType();
    }

    /**
     * Create an instance of {@link CimHexBinary }
     */
    public CimHexBinary createCimHexBinary() {
        return new CimHexBinary();
    }

    /**
     * Create an instance of {@link AutomaticRecoveryAction }
     */
    public AutomaticRecoveryAction createAutomaticRecoveryAction() {
        return new AutomaticRecoveryAction();
    }

    /**
     * Create an instance of {@link CimUnsignedInt }
     */
    public CimUnsignedInt createCimUnsignedInt() {
        return new CimUnsignedInt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "ElementName")
    public JAXBElement<CimString> createElementName(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._ElementName_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link CIMResourceAllocationSettingDataType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "CIM_ResourceAllocationSettingData")
    public JAXBElement<CIMResourceAllocationSettingDataType> createCIMResourceAllocationSettingData(
        final CIMResourceAllocationSettingDataType value) {
        return new JAXBElement<CIMResourceAllocationSettingDataType>(ObjectFactory._CIMResourceAllocationSettingData_QNAME,
            CIMResourceAllocationSettingDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ProductSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "ProductSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<ProductSectionType> createProductSection(final ProductSectionType value) {
        return new JAXBElement<ProductSectionType>(ObjectFactory._ProductSection_QNAME, ProductSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/common", name = "DefaultValue")
    public JAXBElement<Object> createDefaultValue(final Object value) {
        return new JAXBElement<Object>(ObjectFactory._DefaultValue_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "RecoveryFile")
    public JAXBElement<CimString> createRecoveryFile(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._RecoveryFile_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link VirtualSystemCaption }
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Caption")
    public VirtualSystemCaption createVirtualSystemCaption(final VirtualSystemCaption.Type value) {
        return new VirtualSystemCaption(value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link CIMVirtualSystemSettingDataType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "CIM_VirtualSystemSettingData")
    public JAXBElement<CIMVirtualSystemSettingDataType> createCIMVirtualSystemSettingData(
        final CIMVirtualSystemSettingDataType value) {
        return new JAXBElement<CIMVirtualSystemSettingDataType>(ObjectFactory._CIMVirtualSystemSettingData_QNAME,
            CIMVirtualSystemSettingDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link InstallSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "InstallSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<InstallSectionType> createInstallSection(final InstallSectionType value) {
        return new JAXBElement<InstallSectionType>(ObjectFactory._InstallSection_QNAME, InstallSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ConfigurationFile")
    public JAXBElement<CimString> createConfigurationFile(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._ConfigurationFile_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "PoolID")
    public JAXBElement<CimString> createPoolID(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._PoolID_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedInt }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "Weight")
    public JAXBElement<CimUnsignedInt> createWeight(final CimUnsignedInt value) {
        return new JAXBElement<CimUnsignedInt>(ObjectFactory._Weight_QNAME, CimUnsignedInt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link VirtualSystemCollectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "VirtualSystemCollection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Content")
    public JAXBElement<VirtualSystemCollectionType> createVirtualSystemCollection(final VirtualSystemCollectionType value) {
        return new JAXBElement<VirtualSystemCollectionType>(ObjectFactory._VirtualSystemCollection_QNAME,
            VirtualSystemCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link VirtualSystemType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "VirtualSystem", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Content")
    public JAXBElement<VirtualSystemType> createVirtualSystem(final VirtualSystemType value) {
        return new JAXBElement<VirtualSystemType>(ObjectFactory._VirtualSystem_QNAME, VirtualSystemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "SuspendDataRoot")
    public JAXBElement<CimString> createSuspendDataRoot(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._SuspendDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "VirtualSystemIdentifier")
    public JAXBElement<CimString> createVirtualSystemIdentifier(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._VirtualSystemIdentifier_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "AddressOnParent")
    public JAXBElement<CimString> createAddressOnParent(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._AddressOnParent_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiskSectionType }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "DiskSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<DiskSectionType> createDiskSection(final DiskSectionType value) {
        return new JAXBElement<DiskSectionType>(ObjectFactory._DiskSection_QNAME, DiskSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "Parent")
    public JAXBElement<CimString> createParent(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._Parent_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "ResourceSubType")
    public JAXBElement<CimString> createResourceSubType(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._ResourceSubType_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link AutomaticShutdownAction }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticShutdownAction")
    public JAXBElement<AutomaticShutdownAction> createAutomaticShutdownAction(final AutomaticShutdownAction value) {
        return new JAXBElement<AutomaticShutdownAction>(ObjectFactory._AutomaticShutdownAction_QNAME,
            AutomaticShutdownAction.class, null, value);
    }

    /**
     * Create an instance of {@link VirtualSystemDescription }
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Description")
    public VirtualSystemDescription createVirtualSystemDescription(final CimString value) {
        return new VirtualSystemDescription(value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedLong }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "Limit")
    public JAXBElement<CimUnsignedLong> createLimit(final CimUnsignedLong value) {
        return new JAXBElement<CimUnsignedLong>(ObjectFactory._Limit_QNAME, CimUnsignedLong.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "SwapFileDataRoot")
    public JAXBElement<CimString> createSwapFileDataRoot(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._SwapFileDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link DeploymentOptionSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "DeploymentOptionSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<DeploymentOptionSectionType> createDeploymentOptionSection(final DeploymentOptionSectionType value) {
        return new JAXBElement<DeploymentOptionSectionType>(ObjectFactory._DeploymentOptionSection_QNAME,
            DeploymentOptionSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link StartupSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "StartupSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<StartupSectionType> createStartupSection(final StartupSectionType value) {
        return new JAXBElement<StartupSectionType>(ObjectFactory._StartupSection_QNAME, StartupSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link VirtualSystemInstanceID }
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "InstanceID")
    public VirtualSystemInstanceID createVirtualSystemInstanceID(final CimString value) {
        return new VirtualSystemInstanceID(value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link CimUnsignedShort }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticStartupActionSequenceNumber")
    public JAXBElement<CimUnsignedShort> createAutomaticStartupActionSequenceNumber(final CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(ObjectFactory._AutomaticStartupActionSequenceNumber_QNAME,
            CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimBoolean }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "AutomaticAllocation")
    public JAXBElement<CimBoolean> createAutomaticAllocation(final CimBoolean value) {
        return new JAXBElement<CimBoolean>(ObjectFactory._AutomaticAllocation_QNAME, CimBoolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticStartupActionDelay")
    public JAXBElement<CimDateTime> createAutomaticStartupActionDelay(final CimDateTime value) {
        return new JAXBElement<CimDateTime>(ObjectFactory._AutomaticStartupActionDelay_QNAME, CimDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedLong }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "Reservation")
    public JAXBElement<CimUnsignedLong> createReservation(final CimUnsignedLong value) {
        return new JAXBElement<CimUnsignedLong>(ObjectFactory._Reservation_QNAME, CimUnsignedLong.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link VirtualHardwareSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "VirtualHardwareSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<VirtualHardwareSectionType> createVirtualHardwareSection(final VirtualHardwareSectionType value) {
        return new JAXBElement<VirtualHardwareSectionType>(ObjectFactory._VirtualHardwareSection_QNAME,
            VirtualHardwareSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "VirtualSystemType")
    public JAXBElement<CimString> createVirtualSystemType(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._VirtualSystemType_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "OtherResourceType")
    public JAXBElement<CimString> createOtherResourceType(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._OtherResourceType_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "Connection")
    public JAXBElement<CimString> createConnection(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._Connection_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ResourceAllocationSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "ResourceAllocationSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<ResourceAllocationSectionType> createResourceAllocationSection(final ResourceAllocationSectionType value) {
        return new JAXBElement<ResourceAllocationSectionType>(ObjectFactory._ResourceAllocationSection_QNAME,
            ResourceAllocationSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringsType }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "Strings")
    public JAXBElement<StringsType> createStrings(final StringsType value) {
        return new JAXBElement<StringsType>(ObjectFactory._Strings_QNAME, StringsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SectionType }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "Section")
    public JAXBElement<SectionType> createSection(final SectionType value) {
        return new JAXBElement<SectionType>(ObjectFactory._Section_QNAME, SectionType.class, null, value);
    }

    /**
     * Create an instance of {@link ResourceAllocationCaption }
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "Caption")
    public ResourceAllocationCaption createResourceAllocationCaption(final ResourceAllocationCaption.Type value) {
        return new ResourceAllocationCaption(value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link AutomaticRecoveryAction }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticRecoveryAction")
    public JAXBElement<AutomaticRecoveryAction> createAutomaticRecoveryAction(final AutomaticRecoveryAction value) {
        return new JAXBElement<AutomaticRecoveryAction>(ObjectFactory._AutomaticRecoveryAction_QNAME,
            AutomaticRecoveryAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvelopeType }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "Envelope")
    public JAXBElement<EnvelopeType> createEnvelope(final EnvelopeType value) {
        return new JAXBElement<EnvelopeType>(ObjectFactory._Envelope_QNAME, EnvelopeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link AutomaticStartupAction }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticStartupAction")
    public JAXBElement<AutomaticStartupAction> createAutomaticStartupAction(final AutomaticStartupAction value) {
        return new JAXBElement<AutomaticStartupAction>(ObjectFactory._AutomaticStartupAction_QNAME,
            AutomaticStartupAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ConfigurationID")
    public JAXBElement<CimString> createConfigurationID(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._ConfigurationID_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "VirtualQuantityUnits")
    public JAXBElement<CimString> createVirtualQuantityUnits(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._VirtualQuantityUnits_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link OperatingSystemSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "OperatingSystemSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<OperatingSystemSectionType> createOperatingSystemSection(final OperatingSystemSectionType value) {
        return new JAXBElement<OperatingSystemSectionType>(ObjectFactory._OperatingSystemSection_QNAME,
            OperatingSystemSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "ResourceType")
    public JAXBElement<ResourceType> createResourceType(final ResourceType value) {
        return new JAXBElement<ResourceType>(ObjectFactory._ResourceType_QNAME, ResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link VirtualSystemElementName }
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ElementName")
    public VirtualSystemElementName createVirtualSystemElementName(final CimString value) {
        return new VirtualSystemElementName(value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "AllocationUnits")
    public JAXBElement<CimString> createAllocationUnits(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._AllocationUnits_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link ConsumerVisibility }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "ConsumerVisibility")
    public JAXBElement<ConsumerVisibility> createConsumerVisibility(final ConsumerVisibility value) {
        return new JAXBElement<ConsumerVisibility>(ObjectFactory._ConsumerVisibility_QNAME, ConsumerVisibility.class, null,
            value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Notes")
    public JAXBElement<CimString> createNotes(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._Notes_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "CreationTime")
    public JAXBElement<CimDateTime> createCreationTime(final CimDateTime value) {
        return new JAXBElement<CimDateTime>(ObjectFactory._CreationTime_QNAME, CimDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "SnapshotDataRoot")
    public JAXBElement<CimString> createSnapshotDataRoot(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._SnapshotDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedLong }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "VirtualQuantity")
    public JAXBElement<CimUnsignedLong> createVirtualQuantity(final CimUnsignedLong value) {
        return new JAXBElement<CimUnsignedLong>(ObjectFactory._VirtualQuantity_QNAME, CimUnsignedLong.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "Content")
    public JAXBElement<ContentType> createContent(final ContentType value) {
        return new JAXBElement<ContentType>(ObjectFactory._Content_QNAME, ContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "InstanceID")
    public JAXBElement<CimString> createInstanceID(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._InstanceID_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ConfigurationDataRoot")
    public JAXBElement<CimString> createConfigurationDataRoot(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._ConfigurationDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "HostResource")
    public JAXBElement<CimString> createHostResource(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._HostResource_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "Description")
    public JAXBElement<CimString> createDescription(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._Description_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "LogDataRoot")
    public JAXBElement<CimString> createLogDataRoot(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._LogDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimBoolean }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "AutomaticDeallocation")
    public JAXBElement<CimBoolean> createAutomaticDeallocation(final CimBoolean value) {
        return new JAXBElement<CimBoolean>(ObjectFactory._AutomaticDeallocation_QNAME, CimBoolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MappingBehavior }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "MappingBehavior")
    public JAXBElement<MappingBehavior> createMappingBehavior(final MappingBehavior value) {
        return new JAXBElement<MappingBehavior>(ObjectFactory._MappingBehavior_QNAME, MappingBehavior.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", name = "Address")
    public JAXBElement<CimString> createAddress(final CimString value) {
        return new JAXBElement<CimString>(ObjectFactory._Address_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link AnnotationSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "AnnotationSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<AnnotationSectionType> createAnnotationSection(final AnnotationSectionType value) {
        return new JAXBElement<AnnotationSectionType>(ObjectFactory._AnnotationSection_QNAME, AnnotationSectionType.class,
            null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link NetworkSectionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "NetworkSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<NetworkSectionType> createNetworkSection(final NetworkSectionType value) {
        return new JAXBElement<NetworkSectionType>(ObjectFactory._NetworkSection_QNAME, NetworkSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EulaSectionType }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/ovf/envelope/1", name = "EulaSection", substitutionHeadNamespace = "http://schemas.dmtf.org/ovf/envelope/1", substitutionHeadName = "Section")
    public JAXBElement<EulaSectionType> createEulaSection(final EulaSectionType value) {
        return new JAXBElement<EulaSectionType>(ObjectFactory._EulaSection_QNAME, EulaSectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/common", name = "CIM_DateTime", scope = CimDateTime.class)
    public JAXBElement<String> createCimDateTimeCIMDateTime(final String value) {
        return new JAXBElement<String>(ObjectFactory._CimDateTimeCIMDateTime_QNAME, String.class, CimDateTime.class, value);
    }

}
