//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 02:54:08 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.dmtf.org/ovf/envelope/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ow2.sirocco.cloudmanager.service.ovf.datamodel;

