#!/bin/sh
#
#
# SIROCCO
# Copyright (C) 2011 France Telecom
# Contact: sirocco@ow2.org
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
# USA
#
#  $Id$
#
#


cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true;
esac

if [ -z "$SIROCCO_TOOLS_HOME" ];  then
  echo "Please set SIROCCO_TOOLS_HOME"
  exit 1
fi

PROPERTIES_FILE=$SIROCCO_TOOLS_HOME/etc/sirocco_tools.properties
LOGGING_CONFIG_FILE=$SIROCCO_TOOLS_HOME/etc/logging.properties

CLASSPATH="$SIROCCO_TOOLS_HOME/lib/*"

if $cygwin; then
  CLASSPATH=`cygpath --path -w "$CLASSPATH"`
  CLASSPATH=";$CLASSPATH"
  PROPERTIES_FILE=`cygpath -w $PROPERTIES_FILE`
  LOGGING_CONFIG_FILE=`cygpath  -w $LOGGING_CONFIG_FILE`
fi

java -cp "$CLASSPATH" -Ddefault.properties=$PROPERTIES_FILE -Djava.util.logging.config.file=$LOGGING_CONFIG_FILE org.ow2.sirocco.cloudmanager.api.tools.ListPerfMetrics "$@"
